AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Populate a DynamoDB Table from a Custom Resource

Resources:
  DynamoBucket:
    Type: "AWS::S3::Bucket"

  FrenchDynamoTable:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - DynamoBucket
      - PopulateDynamoTable
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ImportSourceSpecification:
        InputCompressionType: "NONE"
        InputFormat: "DYNAMODB_JSON"
        S3BucketSource:
          S3Bucket: !Ref DynamoBucket
          S3KeyPrefix: "phrases.json"

  PopulateDynamoTableLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Provides permissions for internally-invoked Lambda resources
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"
        - PolicyName: S3PolicyPopulateDynamoTable
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:DeleteBucket
                Resource:
                  - !Join ["", ["arn:aws:s3:::", !Ref DynamoBucket]]
                  - !Join ["", ["arn:aws:s3:::", !Ref DynamoBucket, "/*"]]
        - PolicyName: TranslateDynamoPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - translate:TranslateText
                Resource: "*"
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:Invoke*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource: "*"

  PopulateDynamoTableLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "PopulateDynamoTable.handler"
      Runtime: nodejs18.x
      Timeout: "90"
      CodeUri: src/
      Role: !GetAtt PopulateDynamoTableLambdaRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref DynamoBucket

  PopulateDynamoTable:
    Type: Custom::PopulateDynamoTable
    DependsOn:
      - DynamoBucket
    Properties:
      ServiceToken: !GetAtt PopulateDynamoTableLambda.Arn
